name: ${name}
version: ${version}
main: tf.tuff.TuffX
author: Potato
authors: [Potato, SyntaxSavy, llucasandersen, coleis1op, UplandJacob]
api-version: 1.18
depend: [ViaVersion, ViaBackwards, packetevents]

commands:
    viablocks:
        description: Main command for ViaBlocks.
        usage: /viablocks <get|refresh>
        permission: tuffx.viablocks.command
    tuffx:
        description: Main command for TuffX.
        usage: /tuffx <reload>
    restrictions:
        description: Allow or disallow TuffClient modules.
        usage: /restrictions <allow|disallow> <module>

permissions:
    tuffx.reload:
        description: Allows use of the /tuffx reload subcommand.
        default: op
    tuffx.viablocks.command:
        description: Allows use of the /viablocks command.
        default: op
    tuffx.viablocks.command.get:
        description: Allows use of the /viablocks get subcommand.
        default: op
    tuffx.viablocks.command.refresh:
        description: Allows use of the /viablocks refresh subcommand.
        default: op
    tuffx.restrictions.command:
        description: Allows use of the /restrictions command.
        default: op
    tuffx.restrictions.command.allow:
        description: Allows use of the /restrictions allow subcommand.
        default: op
    tuffx.restrictions.command.disallow:
        description: Allows use of the /restrictions disallow subcommand.
        default: op
